drop table ACTUAL;

/*==============================================================*/
/* Table: ACTUAL                                                */
/*==============================================================*/
create table ACTUAL (
FISCALPERIODID integer,
ORUGROUPID integer,
BUGROUPID integer,
FISCALPERIODID_DT date,
OHREQUID integer,
FSITEMID string,
MAG string,
MAG_BU string,
ORUGROUP string,
CURRENCYID integer,
DATASOURCEPK integer,
AMT_EUR decimal(31,6),
AMT_LOCAL decimal(38,6),
AMT_OOH_EUR decimal(31,6),
AMT_OOH_LOCAL decimal(38,6),
SALESDOC_ITEM string,
SALESDOC string,
SALESDOC_ITEM_ONLY string,
DOCUMENT_CURRENCY string,
LOCAL_CURRENCY string,
ACCOUNTDOCTYPEID string,
PMALAYER string,
MATERIAL string,
BUSINESS_AREA string,
WBS_ELEMENT string,
SOLD_TO_PARTY string,
SOLD_TO_PARTY_NAME string,
SHIP_TO_PARTY string,
SHIP_TO_PARTY_NAME string,
OH_TABLE string,
WBS_GROUP string,
SDITEM_FSRDT date,
SDITEMCONTRACTENDD date,
SDITEM_ACTUALSALES date,
SDITEM_CREATEONDT date,
SDITEMCONTRACTSTAR date,
DETAILJOIN_BIT integer,
NEGATIVE_DOCNUM_OO boolean,
NEGATIVE_WBS_GROUP boolean,
ORDERSTATUSFK integer,
PROJECT_MANAGER_RD date,
REQUESTED_RDD date,
SALES_GROUP string,
OH_TIMESTAMP_DT date,
SALES_ORDER_ITEM__ string,
PMAGEOCODE string,
CS_ARCHTYPE string,
DOCUMENT_DATE date,
CUSTOMER_ACCEPTANC date,
OPEN_CLOSED_FLAG string,
OOH_SCHEDULED_UNSC string,
ORIGINAL_SALESDOC string,
POSTING_INDICATOR string,
MEDIUM_TEXT string,
ORG_SALESDOC_FINAL string,
ORG_SALESDOC_NEGAT boolean,
ACCOUNT_MANAGER string,
AMT_USD decimal(38,6),
CREATEDONDT date,
OITQUANTITY decimal(38,6),
AMT_AOP_OOB decimal(38,6),
AMT_AOP_OOH decimal(38,6),
ZERO_ELIM_FLAG boolean
);
