drop table DIM_GEOGRAPHY;

/*==============================================================*/
/* Table: DIM_GEOGRAPHY                                         */
/*==============================================================*/
create table DIM_GEOGRAPHY (
FISCALYEAR string,
GEOGRAPHYPK string,
WORLD string,
BMC_CODE string,
BMC_MARKETS string,
COUNTRY_CODE string,
COUNTRY string,
COUNTRY_GROUP_CODE string,
COUNTRYGROUPDESCRI string,
DISTRICT string,
DISTRICTDESCRIPTIO string,
SALESAREA string,
SALESAREADESCRIPTI string,
SALESAREAGROUP string,
SALESAREAGROUPDESC string,
ORUID string,
NPMAGEOGR string,
OHREQUID string,
DISTRICTCUSTOMERCO string,
DISTRICTCUSTOMERDE string,
LEVEL1 string,
LEVEL1_DESC string,
LEVEL1_SORT string,
LEVEL6 string,
LEVEL6_DESC string,
LEVEL6_SORT string,
LEVEL5 string,
LEVEL5_DESC5 string,
LEVEL5_SORT string,
LEVEL4 string,
LEVEL4_DESC string,
LEVEL4_SORT string,
LEVEL3 string,
LEVEL3_DESC string,
LEVEL3_SORT string,
LEVEL2 string,
LEVEL2_DESC string,
LEVEL2_SORT string
);
