drop table DIM_MRU_UNIT_HIERA;

/*==============================================================*/
/* Table: DIM_MRU_UNIT_HIERA                                    */
/*==============================================================*/
create table DIM_MRU_UNIT_HIERA (
FISCALYEAR string,
BUGROUP string,
BUGROUPID string,
BUGROUP_DESCRIPTIO string,
BUGROUP_FULLDESCRI string,
CUSTOM_CS_EQUIP_L1 string,
CUSTOM_CS_EQUIP_L2 string,
ROWID string,
LEVELNO string,
PRODUCTDETAILLEVEL string,
ACTIVE string,
BMCBUSINESS string,
BMCBUSINESS_DESCRI string,
BMC_ACTIVE string,
BMC_GLOBAL_BUS_IDC string,
PLANNING_LEVEL string,
PLANNING_LEVEL1 string,
SECTOR string,
PD string,
MRU string,
MRU_ACTIVE string,
ACQ_IDC string,
VALIDITY string,
ISTECHNICALMRU string,
SUCCESSOR string,
BMCBUSINESS_CODE string,
BMCBUSINESS_CODE_D string,
BMCBUSINESS_SEC_L1 string,
BMCBUSINESS_SEC_DE string,
BMCBUSINESS_SEC_L2 string,
BMCBUSINESS_SECTOR string,
BMCBUSINESS_GROUP string,
BMCBUSINESS_GROUP_ string,
BUSINESSMODEL string,
DELIVERYMODEL string,
MODDT_UTC string,
EF_MODEL_BU string,
DA_INDICATOR string,
LEVEL1 string,
LEVEL1_DESC string,
LEVEL1_SORT string,
LEVEL6 string,
LEVEL6_DESC string,
LEVEL6_SORT string,
LEVEL5 string,
LEVEL5_DESC5 string,
LEVEL5_SORT string,
LEVEL4 string,
LEVEL4_DESC string,
LEVEL4_SORT string,
LEVEL3 string,
LEVEL3_DESC string,
LEVEL3_SORT string,
LEVEL2 string,
LEVEL2_DESC string,
LEVEL2_SORT string,
LEVEL7 string,
LEVEL7_DESC string,
LEVEL7_SORT string,
LEVEL8 string,
LEVEL8_DESC string,
LEVEL8_SORT string,
LEVEL9 string,
LEVEL9_DESC string,
LEVEL9_SORT string,
LEVEL10 string,
LEVEL10_DESC string,
LEVEL10_SORT string,
LEVEL11 string,
LEVEL11_DESC string,
LEVEL11_SORT string
);
