drop table o2c.tbl_item;

/*==============================================================*/
/* Table: tbl_item                                              */
/*==============================================================*/
create table if not exists o2c.tbl_item (
   Kernel_Name          STRING,
   Client_Name          STRING,
   Material             STRING,
   Language             STRING,
   Created_On           DATE,
   Created_By           STRING,
   Last_Change          DATE,
   Changed_By           STRING,
   Complete_Status      STRING,
   Maint_Status         STRING,
   DF_Client_Level      STRING,
   Material_Type        STRING,
   Industry_Sector      STRING,
   Material_Grp         STRING,
   Old_Material_No      STRING,
   Base_Unit            STRING,
   Order_Unit           STRING,
   Doc_No               STRING,
   Doc_Type             STRING,
   Doc_Version          STRING,
   Page_Format          STRING,
   Doc_Change_No        STRING,
   Page_No              STRING,
   Prodn_Insp_Memo      STRING,
   Page_Format_Prod_Memo STRING,
   Size_Dimensions      STRING,
   Basic_Material       STRING,
   Ind_Std_Desc         STRING,
   Lab_Office           STRING,
   Purch_Value_Key      STRING,
   Gross_Weight         DECIMAL(13,3),
   Net_Weight           DECIMAL(13,3),
   Weight_Unit          STRING,
   Volume               DECIMAL(13,3),
   Volume_Unit          STRING,
   Container            STRING,
   Stor_Cond            STRING,
   Temperature          STRING,
   Low_Level_Code       STRING,
   Trans_Grp            STRING,
   Haz_Matl_No          STRING,
   Division             STRING,
   Competitor           STRING,
   GR_Slips_Quantity    STRING,
   Procure_Rule         STRING,
   Label_Type           STRING,
   Label_Form           STRING,
   EAN_UPC              STRING,
   EAN_Category         STRING,
   Length               DECIMAL(13,3),
   Width                DECIMAL(13,3),
   Height               DECIMAL(13,3),
   Unit                 STRING,
   Prod_Hierarchy       STRING,
   CAD_Indicator        STRING,
   QM_Procurement       STRING,
   Allowed_Pkg_Wt       DECIMAL(13,3),
   Unit_Of_Weight       STRING,
   Allowed_Volume       DECIMAL(13,3),
   Allod_Volume_Unit    STRING,
   Excess_Wt_Tolerance  DECIMAL(3,0),
   Excess_Volume_Tol    DECIMAL(3,0),
   Revision_Level       STRING,
   Configurable         STRING,
   BatchManagement      STRING,
   Packag_Mat_Type      STRING,
   Stacking_Factor      INT,
   Mat_Grp_Pck_Mat      STRING,
   Authorization_Grp    STRING,
   Valid_From           DATE,
   Valid_To             DATE,
   Ext_Matl_Grp         STRING,
   Cross_Plant_CM       STRING,
   Matl_Category        STRING,
   X_Plant_Status       STRING,
   X_DChain_Status      STRING,
   Valid_From_Cross_Plant DATE,
   Valid_From_X_Distr_Chain DATE,
   Tax_Class            STRING,
   Catalog_Profile      STRING,
   Rem_Shelf_Life       DECIMAL(4,0),
   Tot_Shelf_Life       DECIMAL(4,0),
   Storage_Percent      DECIMAL(3,0),
   Content_Unit         STRING,
   Int_Object_No        STRING,
   Envt_Relevant        STRING,
   Prod_Allocation      STRING,
   Pricing_Profile      STRING,
   Disc_In_Kind         STRING,
   Mfr_Part_No          STRING,
   Manufacturer_No      STRING,
   Int_Mat_No           STRING,
   Mfr_Part_Profile     STRING,
   DGIndProfile         STRING,
   Highly_Viscous       STRING,
   In_Bulk_Liquid       STRING,
   Batch_Rec_Req        STRING,
   Rounding_Rule        STRING,
   Gen_Item_Cat_Grp     STRING,
   Material_Locked      STRING,
   Astmt_List_Type      STRING,
   Expiratn_Date        STRING,
   WH_Stor_Cond         STRING,
   WH_Mat_Grp           STRING,
   Handling_Ind         STRING,
   Haz_Sub              STRING,
   Mat_Freight_Grp      STRING,
   Qual_Insp_Grp        STRING,
   Phys_Commodity       STRING,
   Packaging_Code       STRING,
   DG_Pckg_Status       STRING,
   Return_Code          STRING,
   Creation_Status      STRING,
   Color                STRING,
   Care_Code            STRING,
   Brand                STRING,
   Service_Indicator    STRING,
   ZMAT_Type            STRING,
   Sales_Indicator      STRING,
   Catalog_Item         STRING,
   Material_Description STRING,
   Description_Upper_Case STRING,
   bgCode               STRING,
   bgName               STRING,
   buCode               STRING,
   buName               STRING,
   magCode              STRING,
   magName              STRING,
   agCode               STRING,
   agName               STRING,
   change_type          STRING,
   `timeStamp`          TIMESTAMP,
   minimum_temperature__ STRING,
   maximum_temperature__ STRING,
   uom_for_temperature__ STRING,
   minimum_humidity__   STRING,
   maximum_humidity__   STRING,
   uom_for_humidity__   STRING,
   minimum_pressure__   STRING,
   maximum_pressure__   STRING,
   uom_for_pressure__   STRING,
   special_storage_condition__ STRING,
   constraint FK_ITEM_MATERIALHIERARCHY foreign key () references o2c.tbl_material_hierarchy () disable novalidate,
   constraint FK_ITEM_PRODUCTCOSTING foreign key () references tbl_product_costing () disable novalidate,
   constraint FK_ITEM_WAREHOUSE_MANAGEMENT_INVENTORY foreign key () references o2c.tbl_warehouse_management_invent () disable novalidate,
   constraint FK_ITEM_PARTS_LIFECYCLE_MANAGEMENT foreign key () references tbl_parts_lifecycle_management () disable novalidate
)
   USING delta
   LOCATION 'abfss://shared@az21q1datalakewe.dfs.core.windows.net/IM/O2C/silverl2/AzureDataLake/MasterData/T_MBP_Item'
   TBLPROPERTIES (
     'delta.autoOptimize.autoCompact' = 'true',
     'delta.autoOptimize.optimizeWrite' = 'true',
     'delta.enableChangeDataFeed' = 'true',
     'delta.minReaderVersion' = '1',
     'delta.minWriterVersion' = '4');
