drop table o2c.tbl_purchase_info_record;

/*==============================================================*/
/* Table: tbl_purchase_info_record                              */
/*==============================================================*/
create table if not exists o2c.tbl_purchase_info_record (
   Kernel_Name          STRING,
   Client               STRING,
   Purchase_Info_record STRING,
   Info_Record          STRING,
   Purchasing_Org       STRING,
   Infotype             STRING,
   Plant                STRING,
   Material             STRING,
   Material_Grp         STRING,
   Vendor               STRING,
   Complete             STRING,
   Rec_Crtd_On          DATE,
   Rec_Crtd_by          STRING,
   Info_Short_Text      STRING,
   Sort_Term            STRING,
   Order_Unit           STRING,
   Equal_To             DECIMAL(5,0),
   Denominator          DECIMAL(5,0),
   Vendor_Mat_No        STRING,
   Sls_person           STRING,
   Telephone            STRING,
   "1st_Rem_Exped"      DECIMAL(3,0),
   "2nd_Rem_Exped"      DECIMAL(3,0),
   "3rd_Rem_Exped"      DECIMAL(3,0),
   Certificate_No       STRING,
   Certif_Valid_to      DATE,
   Ctry_of_Origin       STRING,
   Certif_Cat           STRING,
   Number               STRING,
   Base_Unit            STRING,
   Region               STRING,
   Var_Order_Unit       STRING,
   Vendor_Subrange      STRING,
   VSR_Sort_No          STRING,
   Vendor_Mat_Grp       STRING,
   Return_Agmt          STRING,
   Available_from       DATE,
   Available_to         DATE,
   Prior_Vendor         STRING,
   Points               DECIMAL(13,3),
   Points_unit          STRING,
   Regular_Vendor       STRING,
   Manufacturer         STRING,
   Purch_org_data       STRING,
   Org_Data_Crtd_On     DATE,
   Org_Data_Crtd_by     STRING,
   Purch_Grp            STRING,
   Currency             STRING,
   V_Rebate_Ind         STRING,
   Quantity_Rebate      STRING,
   Minimum_Qty          DECIMAL(13,3),
   Standard_Qty         DECIMAL(13,3),
   Pl_Deliv_Time        DECIMAL(3,0),
   Overdeliv_Tol        DECIMAL(3,1),
   Unlimited            STRING,
   Underdel_Tol         DECIMAL(3,1),
   Quotation            STRING,
   Quotation_from       DATE,
   RFQ                  STRING,
   Item                 STRING,
   Rejection_Ind        STRING,
   Period_from          DATE,
   Period_to            DATE,
   Amort_plan_qty       DECIMAL(15,3),
   Amort_plan_val       DECIMAL(15,2),
   Amort_Act_qty        DECIMAL(15,3),
   Amort_act_value      DECIMAL(15,2),
   Amort_reset          STRING,
   Doc_Category         STRING,
   Pur_Doc              STRING,
   Pur_Doc_Item         STRING,
   Doc_Date             DATE,
   Net_Price            DECIMAL(11,2),
   Price_Unit           DECIMAL(5,0),
   Order_Price_Un       STRING,
   Valid_to             DATE,
   Numerator_Qty_Conv   DECIMAL(5,0),
   Denominator_Qty_Conv DECIMAL(5,0),
   No_Mat_Text          STRING,
   GR_Based_IV          STRING,
   Effect_Price         DECIMAL(11,2),
   Condition_Grp        STRING,
   No_Cash_Disc         STRING,
   Acknowl_Reqd         STRING,
   Tax_code             STRING,
   Valuation_Type       STRING,
   Sett_Grp_1           STRING,
   Shipping_Instr       STRING,
   "Procedure"          STRING,
   Conf_Control         STRING,
   Pr_Date_Cat          STRING,
   Incoterms            STRING,
   Incoterms_2          STRING,
   No_ERS               STRING,
   Sett_Grp_2           STRING,
   Sett_Grp_3           STRING,
   No_Subs_Sett         STRING,
   Rem_Shelf_Life       DECIMAL(4,0),
   Prod_Version         STRING,
   Max_Pur_Ordr_Qty     DECIMAL(13,3),
   Rnding_Profile       STRING,
   UoM_Grp              STRING,
   NCM_Code             STRING,
   Create_Ref_Doc       STRING,
   Period_Ind           STRING,
   RT_Consumption       STRING,
   RMA_Required         STRING,
   Diff_Invoicing       STRING,
   Inco_Version         STRING,
   Inco_Loc_1           STRING,
   Inco_Loc_2           STRING,
   MRPind               STRING,
   Stock_Seg_Rel_Ind    STRING,
   Transportation_Chain STRING,
   Staging_Time         DECIMAL(3,0),
   change_type          STRING,
   "timeStamp"          TIMESTAMP,
   constraint FK_PURCHASEINFORECORD_ITEM foreign key (Kernel_Name, Material, Material_Grp, Base_Unit, Order_Unit, change_type, "timeStamp") references o2c.tbl_item (Kernel_Name, Material, Material_Grp, Base_Unit, Order_Unit, change_type, "timeStamp") disable novalidate
)
   USING delta
   LOCATION 'abfss://shared@az21q1datalakewe.dfs.core.windows.net/IM/O2C/silverl2/AzureDataLake/PlanToFinishedGoods/T_MBP_Purchase_Info_Record'
   TBLPROPERTIES (
     'delta.autoOptimize.autoCompact' = 'true',
     'delta.autoOptimize.optimizeWrite' = 'true',
     'delta.enableChangeDataFeed' = 'true',
     'delta.minReaderVersion' = '1',
     'delta.minWriterVersion' = '4');
