drop table REVENUEANDPROFITABILITYSOLDTODA;

/*==============================================================*/
/* Table: REVENUEANDPROFITABILITYSOLDTODA                       */
/*==============================================================*/
create table if not exists REVENUEANDPROFITABILITYSOLDTODA (
   ORDER_COUNTRY_CODE   string,
   ORDER_MARKET_CODE    string,
   ORDER_MARKET_NAME    string,
   ORDER_COUNTRY_NAME   string,
   SALES_ORDER_NUMBER   string,
   SALES_ORDER_ITEM_NUMBER string,
   SALES_ORDER_TYPE     string,
   ORDER_BUSINESS_GROUP string,
   ORDER_MAG            string,
   SECTOR_CODE          string,
   BUSINESS_MODEL       string,
   END_CUSTOMER_SALES_ORDER string,
   SALES_AGENT          string,
   SALES_QUANTITY       double,
   BILL_TO_PARTY_NAME   string,
   SOLD_TO_PARTY_NAME   string,
   SHIP_TO_PARTY_NAME   string,
   SOLD_TO_ID           string,
   SHIP_TO_ID           string,
   BILL_TO_PARTY_ID     string,
   FINAL_CUSTOMER_ID    string,
   FINAL_CUSTOMER_NAME  string,
   END_CUSTOMER         string,
   MRU_REPORTING_KEY    string,
   BUSINESS_AREA        string,
   SOLUTION_ID_01       string,
   SOLUTION_ID_02       string,
   SOLUTION_ID_03       string,
   SOLUTION_ID_04       string,
   SOLUTION_ID_08       string,
   IS_SOLUTION_REVENUE  string,
   SOLUTION_FRAMEWORK   string,
   SOLUTION_TYPE        string,
   SOLUTION_NAME        string,
   SOLN_TYPE_OF_SALE_ARCHETYPE_FIN string,
   SOLN_CIRCULAR_REVENUE string,
   RESIDUAL_SOLUTION_TYPE string,
   LONG_TERM_STRATEGIC_PARTNERSHIP string,
   FISCAL_PERIOD        string,
   FISCAL_YEAR          integer,
   FISCAL_QUARTER       integer,
   DISTRICT_NAME        string,
   PMA_LAYER_INDICATOR  string,
   PMA_ADJUSTED_HIERARCHY_LEVEL3 string,
   PMA_ADJUSTED_HIERARCHY_LEVEL4 string,
   PMA_ADJUSTED_HIERARCHY_LEVEL5 string,
   PMA_ADJUSTED_HIERARCHY_LEVEL6 string,
   PMA_ADJUSTED_HIERARCHY_LEVEL7 string,
   PMA_ADJUSTED_HIERARCHY_LEVEL8 string,
   PMA_ADJUSTED_HIERARCHY_LEVEL9 string,
   ORGANISATION_REPORTING_UNIT string,
   LOCAL_CURRENCY_CODE  string,
   CURKEY_GC            string,
   GEOGRAPHY_CODE       string,
   PMA_CUSTOMER         string,
   MATERIAL_CODE        string,
   PMA_NAME1            string,
   OACM_DISTRICT_CODE   string,
   DOCUMENT_QUOTATION_NUMBER string,
   CY_ACTUAL_ITM_USD    double,
   CY_ACTUAL_ITM_AOP_COMPARABLE double,
   LSP_CY_ACTUAL_ITM_USD double,
   LSP_CY_ACTUAL_ITM_AOP_COMPARABL double,
   SOLN_CY_ACTUAL_ITM_USD double,
   SOLN_CY_ACTUAL_ITM_AOP_COMPARAB double,
   ADJUSTED_NET_INCOME_LC double,
   ADJUSTED_EARNINGS_BEFORE_LC double,
   ADJUSTED_GROSS_MARGIN_LC double,
   SALES_TO_THIRDS_LC   double,
   INDUSTRY_COST_LC     double,
   MARKET_COST_LC       double,
   ADJUSTED_NET_INCOME_GC double,
   ADJUSTED_EARNINGS_BEFORE_GC double,
   ADJUSTED_GROSS_MARGIN_GC double,
   SALES_TO_THIRDS_GC   double,
   INDUSTRY_COST_GC     double,
   MARKET_COST_GC       double,
   COMPANY_CODE         string,
   TAX_NUMBER           string,
   BUSINESS_INDICATOR   string,
   constraint FK_REPORTING___JOIN_BASED_ON_SOLD_TO_CUSTOMERS foreign key (SOLD_TO_ID, ORDER_MAG) references CUSTOMERREPORTINGLEVEL (BUSINESS_PARTNER_ROLEID_MP1_ID_, MAIN_ARTICLE_GROUP_CODE) disable novalidate
);
